language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq apache2 
before_script:
  - cd tests
script: phpunit
