language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq apache2
script:
  - phpunit -c tests/unit/ --coverage-clover=coverage.clover
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
notifications:
  - email: true
  - irc: "irc.freenode.org#auraphp"
